{{- if eq .Values.database.lookup.enabled false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.database.lookup.secretKeyRef}}
data:
  connectionString: {{ include "db.ConnectionString" | b64enc}}
---
{{- end }}
{{- if .Values.adminUI.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-ui-password
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "mongo-ui-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 16 | b64enc) }}
  password: {{$password}}
{{- end }}