#output "cluster_id" {
#  description = "EKS cluster ID"
#  value       = module.eks.cluster_id
#}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC issuer"
  value       = module.eks.oidc_provider
}

output "cluster_hash_id" {
  description = "EKS Hash ID"
  value       = local.eks_hash_id
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

#output "additional_security_group_id" {
#  description = "Additional Security group ingress to port 22"
#  value       = aws_security_group.additional.id
#}

#output "kubectl_config" {
#  description = "kubectl config as generated by the module."
#  value       = module.eks.kubeconfig
#}

#output "config_map_aws_auth" {
#  description = "A kubernetes configuration to authenticate to this EKS cluster."
#  value       = module.eks.config_map_aws_auth
#}

output "region" {
  description = "AWS region"
  value       = var.region
}

#output "name" {
#  description = "Name"
#  value       = local.name
#}

output "vpc_id" {
  description = "VPC Id"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "Private Subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "Public subnets"
  value       = module.vpc.public_subnets
}

output "cert_manager_role" {
  description = "The Certificate Manager IRSA"
  value = var.enable_cert_manager ? aws_iam_role.cert-manager[0].arn : ""
}

output "ebs_csi_role" {
  description = "The EBS CSI IRSA"
  value = var.enable_ebs_csi ? aws_iam_role.ebs-csi-role[0].arn : ""
}

output "efs_csi_role" {
  description = "The EFS CSI IRSA"
  value = var.enable_efs_csi ? aws_iam_role.efs-csi-role[0].arn : ""
}

#output "ebs-csi-controller-irsa" {
#  description = "The EBS CSI controller irsa"
#  value       = aws_iam_role.ebs-csi-controller-irsa.arn
#}

#output "ebs_snapshot_policy" {
#  description = "EKS EBS Snapshot Policy"
#  value       = aws_iam_policy.ebs-snapshot.arn
#}

# output "backup_bucket" {
#   description = "Cluster backup bucket"
#   value       = [aws_s3_bucket.backup.arn, aws_s3_bucket.backup.bucket]
# }

# output "cert_manager_role" {
#   description = "EKS Cert Manager Role"
#   value       = aws_iam_role.cert-manager.arn
# }


# output "user_pool_issuer_url" {
#   description = "Cognito Issue Url"
#   value       = aws_cognito_user_pool.cluster_pool.endpoint
# }

# output "user_pool_client_id" {
#   description = "Cognito Client Id"
#   value       = aws_cognito_user_pool_client.cluster_pool_client.id
# }

output "image_repositories" {
  description = "Image repositories"
  value = aws_ecr_repository.repo[*].id
}
