
nameOverride: ""
fullnameOverride: ""

namespace: mongodb
version: "5.0.5"
architecture: ReplicaSet
members: 1
tls:
  enabled: true
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
persistence:
  storageClassName: "csi-sc"
  storageSize: 10Gi
