apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zbi-cluster
spec:
  selfSigned: {}
  acme:
    email: {{ .Values.issuer.email}}
    server: {{ .Values.issuer.server}}
    privateKeySecretRef:
      name: {{ .Values.issuer.secretKeyRef}}
    solvers:
      region: {{requiredEnv "AWS_REGION"}}
      roleArn: {{requiredEnv "DNS_MANAGER_ROLE"}}
      assumeRoleArn: {{requiredEnv "CERT_MANAGER_ROLE"}}
      preferCNAME: true
      evaluateTargetHealth: true
