apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/cert-manager

# patchesJson6902:
# - target:
#     version: v1
#     kind: ServiceAccount
#     name: cert-manager
#   path: service-account.yaml

patchesStrategicMerge:
 - service-account.yaml

resources:
- cluster-issuer.yaml

