{{- if .Values.issuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
{{- if eq .Values.issuer.type "selfsigned"}}
  selfSigned: {}
{{- else}}
  acme:
    email: {{ .Values.issuer.email}}
    server: {{ .Values.issuer.server}}
    privateKeySecretRef:
      name: {{ .Values.issuer.secretKeyRef}}
  {{- with .Values.issuer.solvers}}
    solvers:
      {{- toYaml . | nindent 6 }}
  {{- end}}
{{- end}}
{{- end}}
