name: 'Terraform'

on:
  workflow_dispatch:
    branches: [ "main" ]
  pull_request:

env:
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DNS_MANAGER_ROLE: ${{ secrets.DNS_MANAGER_ROLE }}
  ROUTE53_HOSTED_ZONE: ${{ secrets.ROUTE53_HOSTED_ZONE }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  DB_ADMIN_URL: ${{ vars.DB_ADMIN_URL }}
  GRAFANA_URL: ${{ vars.GRAFANA_URL }}
  GRAFANA_AUTH0_CLIENT_ID: ${{ secrets.GRAFANA_AUTH0_CLIENT_ID }}
  GRAFANA_AUTH0_CLIENT_SECRET: ${{ secrets.GRAFANA_AUTH0_CLIENT_SECRET }}
  GRAFANA_AUTH0_DOMAIN: ${{ vars.GRAFANA_AUTH0_DOMAIN }}
  

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: sandbox

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #- name: list all files
    #  run: ls -al

    - name: Configure AWS credentials for Sandbox
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::169178127784:role/OrganizationAccountAccessRole
        role-duration-seconds: 1200
        role-session-name: zbi-infra

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terrform working directory
    - name: Terraform init
      run: ./aws/deploy.sh --action init

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  run: ./aws/deploy.sh --action format

    # Verify execution plan
    - name: Terraform Plan
      run: ./aws/deploy.sh --action verify --environment sandbox

    - name: Create infrastructure
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: ./aws/deploy.sh --action create --environment sandbox
